### ISSUE TITLE
[Issue] Changing registries of tags doesn't work

### ISSUE THREAD

**Issue by Nekkok** [8s2/Angling#4]
I'm trying to change some biome tag values and they don't apply. I tried to remove sargassum (because reasons, I really love their touch to the world) through this file in a datapack and it isn't working. The same about clams and entities. I'm going to attach everything in case is my fault. And before anything else, I love this mod so much <3 (don't judge my configs, is for a vanilla flavoured modpack I'm trying to do consisting only in adding roe and nautilus mob).

[data.zip](https://github.com/8s2/Angling/files/10797312/data.zip)

**Comment by 8s2** [comment]
Thanks! Your tags should work if you add `"replace": true` in the json of each.

**Comment by Nekkok** [comment]
Yeah, I realized it 10 minutes after... Thank you again haha : )
